# Generated by Django 6.0 on 2025-12-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_course_lecturer_remove_group_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izdatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название издателя', max_length=100, verbose_name='Название издателя')),
                ('geo', models.DateField(blank=True, help_text='Введите место регистрации издателя', null=True, verbose_name='Место регистрации издателя')),
                ('date_of_death', models.DateField(blank=True, help_text='Введите дату смерти', null=True, verbose_name='Дата сметри')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите вид мебели', max_length=200, verbose_name='Вид мебели')),
            ],
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название мебели', max_length=200, verbose_name='Название мебели')),
                ('summary', models.TextField(help_text='Введите краткое описание мебели', max_length=1000, verbose_name='Описание мебели')),
                ('izd', models.ForeignKey(help_text='Выберите издателя мебели', on_delete=django.db.models.deletion.CASCADE, to='catalog.izdatel', verbose_name='Издатель мебели')),
                ('type', models.ForeignKey(help_text='Выберите вид мебели', on_delete=django.db.models.deletion.CASCADE, to='catalog.type', verbose_name='Вид мебели')),
            ],
        ),
    ]
