# Generated by Django 6.0 on 2025-12-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_izdatel_type_mebel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус экземпляра мебели', max_length=200, verbose_name='Статус экземпляра книги')),
            ],
        ),
        migrations.RemoveField(
            model_name='izdatel',
            name='date_of_death',
        ),
        migrations.AlterField(
            model_name='izdatel',
            name='geo',
            field=models.CharField(blank=True, help_text='Введите место регистрации издателя', max_length=120, null=True, verbose_name='Место регистрации издателя'),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Введите инвентарный номер мебели', max_length=20, null=True, verbose_name='Инвентарный номер мебели')),
                ('due_back', models.DateField(blank=True, help_text='Введите конец срока статуса', null=True, verbose_name='Дата окончания статуса')),
                ('mebel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mebel')),
                ('status', models.ForeignKey(help_text='Изменить состояние экземпляра мебели', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status')),
            ],
        ),
    ]
