# Generated by Django 6.0 on 2025-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mstatus_remove_izdatel_date_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='size',
            field=models.IntegerField(help_text='Введите ширина*высота*глубина в сантиметрах', null=True),
        ),
        migrations.AlterField(
            model_name='mstatus',
            name='name',
            field=models.CharField(help_text='Введите статус экземпляра мебели', max_length=200, verbose_name='Статус экземпляра мебели'),
        ),
    ]
