# Generated by Django 6.0 on 2025-12-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_mebel_size_alter_mstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='size',
            field=models.CharField(help_text='Введите ширина*высота*глубина в сантиметрах', null=True),
        ),
    ]
