# Generated by Django 6.0 on 2025-12-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
