# Generated by Django 6.0 on 2026-02-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='mebel',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mebel',
            name='izd',
        ),
        migrations.RemoveField(
            model_name='mebel',
            name='type',
        ),
        migrations.DeleteModel(
            name='MStatus',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='Выберите заказчика книги', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='Izdatel',
        ),
        migrations.DeleteModel(
            name='Mebel',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
